CITY = ['BJ', 'SH', 'GZ', 'SZ', 'HB', 'CC', 'SY', 'TJ']

# String
MAX_LONG_STRING_LEN = 255
MAX_SHORT_STRING_LEN = 255

MIN_LONG_STRING_LEN = 200
MIN_SHORT_STRING_LEN = 200

# Number
MIN_SMALL_INT = 1
MAX_SMALL_INT = 9

MIN_BIG_INT = 100
MAX_BIG_INT = 999

# Workload
INTERNAL_SLEEP_TIME = 0.02

# probe
PROBE_FILE_PREFIX = "./result/sql_"
PROBE_FILE_SUFFIX = ".csv"
PROBE_INTERNAL_TIME = 30
PROBE_TIME_BETWEEN_SQL = 10