CUST_PER_DIST = 3000  # 每个District有多少Customer
DIST_PER_WARE = 10  # 每个Warehouse有多少District
ORD_PER_DIST = 3000  # 每个District有多少的Order
NEW_ORDERS_PER_DISTRICT = 900
# 每一次插入的数目
NUM_ITEMS = 100000
# NUM_ITEMS = 10
NUM_WAREHOUSE = 1

#  Item constants
MIN_IM = 1
MAX_IM = 10000
MIN_PRICE = 1.00
MAX_PRICE = 100.00
MIN_I_NAME = 14
MAX_I_NAME = 24
MIN_I_DATA = 26
MAX_I_DATA = 50
I_ORIGINAL_RATE = 10  # ORIGINAL字符的百分数

# warehouse
INITIAL_W_YTD = 300000.00
MIN_NAME = 6
MAX_NAME = 10
# TAX
MIN_TAX = 0
MAX_TAX = 0.2000
TAX_DECIMALS = 4
# ZIP
ZIP_LENGTH = 9
ZIP_SUFFIX = "11111"
# street
MIN_STREET = 10
MAX_STREET = 20
# city
MIN_CITY = 10
MAX_CITY = 20
STATE = 2

# District
D_INITIAL_YTD = 30000.00

#  Customer constants
CUSTOMERS_PER_DISTRICT = 3000
INITIAL_CREDIT_LIM = 50000.00
MIN_DISCOUNT = 0.0000
MAX_DISCOUNT = 0.5000
DISCOUNT_DECIMALS = 4
INITIAL_BALANCE = -10.00
INITIAL_YTD_PAYMENT = 10.00
INITIAL_PAYMENT_CNT = 1
INITIAL_DELIVERY_CNT = 0
MIN_FIRST = 6
MAX_FIRST = 10
MIDDLE = "OE"
PHONE = 16
MIN_C_DATA = 300
MAX_C_DATA = 500
GOOD_CREDIT = "GC"
BAD_CREDIT = "BC"
C_BAD_CREDIT_RATE = 10  # ORIGINAL字符的百分数

#  History constants
H_MIN_DATA = 12
H_MAX_DATA = 24
H_INITIAL_AMOUNT = 10.00

#  Stock constants
S_MIN_QUANTITY = 10
S_MAX_QUANTITY = 100
S_DIST = 24
STOCK_PER_WAREHOUSE = 100000
S_ORIGINAL_RATE = 10  # ORIGINAL字符的百分数

#  Order constants
MIN_CARRIER_ID = 1
MAX_CARRIER_ID = 10
#  HACK: This is not strictly correct, but it works
NULL_CARRIER_ID = 0
#  o_id < than this value, carrier != null, >= -> carrier == null
NULL_CARRIER_LOWER_BOUND = 2101
MIN_OL_CNT = 5
MAX_OL_CNT = 15
INITIAL_ALL_LOCAL = 1
INITIAL_ORDERS_PER_DISTRICT = 3000

#  Order line constants
INITIAL_QUANTITY = 5
MIN_AMOUNT = 0.01
MAX_OL_QUANTITY = 10

#  Used to generate payment transactions
MIN_PAYMENT = 1.0
MAX_PAYMENT = 5000.0

#  Used to generate stock level transactions
MIN_STOCK_LEVEL_THRESHOLD = 10
MAX_STOCK_LEVEL_THRESHOLD = 20

# Table Names
TABLE_NAME_CUSTOMER = "CUSTOMER"
TABLE_NAME_DISTRICT = "DISTRICT"
TABLE_NAME_HISTORY = "HISTORY"
TABLE_NAME_ITEM = "ITEM"
TABLE_NAME_NEW_ORDER = "NEW_ORDER"
TABLE_NAME_ORDERS = "ORDERS"
TABLE_NAME_ORDER_LINE = "ORDER_LINE"
TABLE_NAME_STOCK = "STOCK"
TABLE_NAME_WAREHOUSE = "WAREHOUSE"

ALL_TABLES = [
    TABLE_NAME_ITEM,
    TABLE_NAME_WAREHOUSE,
    TABLE_NAME_DISTRICT,
    TABLE_NAME_CUSTOMER,
    TABLE_NAME_STOCK,
    TABLE_NAME_ORDERS,
    TABLE_NAME_NEW_ORDER,
    TABLE_NAME_ORDER_LINE,
    TABLE_NAME_HISTORY,
]

ORIGINAL_STRING = "ORIGINAL"

MONEY_DECIMALS = 2
