CUST_PER_DIST = 3000  # 每个District有多少Customer
DIST_PER_WARE = 10  # 每个Warehouse有多少District
ORD_PER_DIST = 3000  # 每个District有多少的Order

#  Item constants
# NUM_ITEMS = 100000
NUM_ITEMS = 10
MIN_IM = 1
MAX_IM = 10000
MIN_PRICE = 1.00
MAX_PRICE = 100.00
MIN_I_NAME = 14
MAX_I_NAME = 24
MIN_I_DATA = 26
MAX_I_DATA = 50

# Table Names
TABLE_NAME_CUSTOMER = "CUSTOMER"
TABLE_NAME_DISTRICT = "DISTRICT"
TABLE_NAME_HISTORY = "HISTORY"
TABLE_NAME_ITEM = "ITEM"
TABLE_NAME_NEW_ORDER = "NEW_ORDER"
TABLE_NAME_ORDERS = "ORDERS"
TABLE_NAME_ORDER_LINE = "ORDER_LINE"
TABLE_NAME_STOCK = "STOCK"
TABLE_NAME_WAREHOUSE = "WAREHOUSE"

ALL_TABLES = [
    TABLE_NAME_ITEM,
    TABLE_NAME_WAREHOUSE,
    TABLE_NAME_DISTRICT,
    TABLE_NAME_CUSTOMER,
    TABLE_NAME_STOCK,
    TABLE_NAME_ORDERS,
    TABLE_NAME_NEW_ORDER,
    TABLE_NAME_ORDER_LINE,
    TABLE_NAME_HISTORY,
]

ORIGINAL_STRING = "ORIGINAL"

MONEY_DECIMALS = 2
