CUST_PER_DIST = 3000        # 每个District有多少Customer
DIST_PER_WARE = 10          # 每个Warehouse有多少District
ORD_PER_DIST = 3000         # 每个District有多少的Order

#  Item constants
# NUM_ITEMS = 100000
NUM_ITEMS = 10
MIN_IM = 1
MAX_IM = 10000
MIN_PRICE = 1.00
MAX_PRICE = 100.00
MIN_I_NAME = 14
MAX_I_NAME = 24
MIN_I_DATA = 26
MAX_I_DATA = 50

# Table Names
TABLENAME_CUSTOMER   = "CUSTOMER"
TABLENAME_DISTRICT   = "DISTRICT"
TABLENAME_HISTORY    = "HISTORY"
TABLENAME_ITEM       = "ITEM"
TABLENAME_NEW_ORDER  = "NEW_ORDER"
TABLENAME_ORDERS     = "ORDERS"
TABLENAME_ORDER_LINE = "ORDER_LINE"
TABLENAME_STOCK      = "STOCK"
TABLENAME_WAREHOUSE  = "WAREHOUSE"

ALL_TABLES = [
    TABLENAME_ITEM,
    TABLENAME_WAREHOUSE,
    TABLENAME_DISTRICT,
    TABLENAME_CUSTOMER,
    TABLENAME_STOCK,
    TABLENAME_ORDERS,
    TABLENAME_NEW_ORDER,
    TABLENAME_ORDER_LINE,
    TABLENAME_HISTORY,
]

ORIGINAL_STRING = "ORIGINAL"

MONEY_DECIMALS = 2
