CITY = ['BJ', 'SH', 'GZ', 'SZ', 'HB', 'CC', 'SY', 'TJ']

# String
MAX_LONG_STRING_LEN = 30
MAX_SHORT_STRING_LEN = 10

MIN_LONG_STRING_LEN = 10
MIN_SHORT_STRING_LEN = 5

# Number
MIN_SMALL_INT = 1
MAX_SMALL_INT = 9

MIN_BIG_INT = 100
MAX_BIG_INT = 999

# Workload
RATE_INSERT = 0.2
RATE_UPDATE = 0.2
RATE_SIMPLE_SEARCH = 0.5
RATE_COMPLEX_SEARCH = 0.1

INTERNAL_SLEEP_TIME = 1