CITY = ['BJ', 'SH', 'GZ', 'SZ', 'HB', 'CC', 'SY', 'TJ']

# String
MAX_LONG_STRING_LEN = 30
MAX_SHORT_STRING_LEN = 10

MIN_LONG_STRING_LEN = 10
MIN_SHORT_STRING_LEN = 5

# Number
MIN_SMALL_INT = 1
MAX_SMALL_INT = 9

MIN_BIG_INT = 100
MAX_BIG_INT = 999